parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(DATABASE_URL_SLAVE): '%env(resolve:DATABASE_URL)%'

doctrine:
    dbal:
        default_connection: 'default'
        connections:
            default:
                schema_filter: '~^(?!messenger_messages|draw_messenger__message|draw_messenger__message_tag)~'
                driver: 'pdo_mysql'
                server_version: '8.0.23'
                logging: true
                charset: 'utf8mb4'
                default_table_options:
                    charset: 'utf8mb4'
                    collation: 'utf8mb4_unicode_ci'
                url: '%env(resolve:DATABASE_URL)%'
                replicas:
                    slave1:
                        url: '%env(resolve:DATABASE_URL_SLAVE)%'

        types:
            bigint: 'Draw\DoctrineExtra\DBAL\Types\BigIntType'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        naming_strategy: 'doctrine.orm.naming_strategy.underscore_number_aware'
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: 'attribute'
                dir: '%kernel.project_dir%/app/src/Entity'
                prefix: 'App\Entity'
                alias: 'App'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: 'pool'
                pool: 'doctrine.system_cache_pool'
            result_cache_driver:
                type: 'pool'
                pool: 'doctrine.result_cache_pool'

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: 'cache.app'
                doctrine.system_cache_pool:
                    adapter: 'cache.system'
