draw_sonata_extra:
  auto_help: true

  can_security_handler:
    prevent_delete_by_relation:
      relations:
        user_tag:
          class: 'App\Entity\Tag'
          related_class: 'App\Entity\User'
          path: 'tags'

  fix_menu_depth: true

  install_assets: true

  list_field_priority:
    default_max_field: 2
    default_field_priorities:
      createdAt: 0

  session_timeout:
    delay: 900
