draw_sonata_extra:
  auto_help: true

  can_security_handler:
    prevent_delete_by_relation:
      entities:
        App\Entity\ChildObject2:
          relations:
            App\Entity\User.onDeleteCascadeConfigOverridden:
              related_class: 'App\Entity\User'
              path: 'onDeleteCascadeConfigOverridden'
            App\Entity\User.onDeleteCascadeConfigPriority:
              related_class: 'App\Entity\User'
              path: 'onDeleteCascadeConfigPriority'
        App\Entity\Tag:
          relations:
            App\Entity\User.tags:
              related_class: 'App\Entity\User'
              path: 'tags'

  fix_menu_depth: true

  install_assets: true

  list_field_priority:
    default_max_field: 2
    default_field_priorities:
      createdAt: 0

  session_timeout:
    delay: 900
