draw_sonata_integration:
  configuration: ~

  console:
    commands:
      'null':
        commandName: 'app:null'
        label: 'Null'

  messenger:
    queue_names: ['default', 'failed']

  user:
    enabled: true
    user_admin_code: App\Sonata\Admin\UserAdmin
    2fa:
      field_positions:
        2fa_enabled:
          list: 'email'
