services:
    _defaults:
        autoconfigure: true
        autowire: true

    messengerTransportDraw: '@messenger.transport.draw'

framework:

    messenger:
        default_bus: 'main.bus'
        transports:
            draw: 'draw://default'
        buses:
            main.bus: ~

draw_messenger:
    broker:
        receivers: ['async']
    sonata:
        transports:
            default:
                transport_name: 'async'
            failed:
                transport_name: 'failed'
            draw:
                transport_name: 'draw'
