draw_sonata_extra:
  auto_help: true

  auto_action: true

  can_security_handler:
    prevent_delete_voter:
      use_cache: false
      entities:
        App\Entity\ChildObject2:
          relations:
            App\Entity\User.onDeleteCascadeConfigOverridden:
              related_class: 'App\Entity\User'
              path: 'onDeleteCascadeConfigOverridden'
        App\Entity\Tag:
          relations:
            App\Entity\User.tags:
              related_class: 'App\Entity\User'
              path: 'tags'

  fix_menu_depth: true

  install_assets: true

  list_field_priority:
    default_max_field: 2
    default_field_priorities:
      createdAt: 0

  notifier: true

  prevent_delete_extension:
    restrict_to_role: 'ROLE_SUPER_ADMIN'

  session_timeout:
    delay: 900
