draw_framework_extra:
  messenger:
    async_routing_configuration: true
    broker:
      contexts:
        default:
          receivers: [ 'async' ]
    doctrine_message_bus_hook: ~
    retry:
      event_driven:
        transports: [ 'async' ]

    serializer_event_dispatcher: ~
    versioning: ~
