services:
    _defaults:
        autoconfigure: true
        autowire: true

    Draw\Component\Messenger\Transport\DrawTransportFactory: ~
    Draw\Component\Messenger\Middleware\ManualTriggerStamperMiddleware: ~
    messengerTransportDraw: '@messenger.transport.draw'

framework:

    messenger:
        default_bus: 'main.bus'
        transports:
            draw: 'draw://default'
        buses:
            main.bus: ~
            messenger.bus.draw:
                middleware:
                    - 'Draw\Component\Messenger\Middleware\ManualTriggerStamperMiddleware'

draw_messenger:
    sonata:
        transports:
            default:
                transport_name: 'async'
            failed:
                transport_name: 'failed'
