parameters:
    jms_serializer.json.visitors.options:
        - JSON_PRETTY_PRINT
        - JSON_UNESCAPED_SLASHES
        - JSON_PRESERVE_ZERO_FRACTION

jms_serializer:
    handlers:
        datetime:
            default_format: 'Y-m-d\TH:i:s.u\Z'

    visitors:
        json_serialization:
            options: '%jms_serializer.json.visitors.options%'
    metadata:
        infer_types_from_doc_block: true

        directories:
            app-entity:
                namespace_prefix: "App\\Entity"
                path: "%kernel.project_dir%/config/serializer/Entity"
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
