version: '3'

services:
  nginx:
    build: .docker/nginx
    ports:
      - 443:443
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/:ro
      - .:/home/wwwroot
      - ./.docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - php

  mysql:
    image: "mysql:8.0.23"
    command: mysqld --sql_mode=""
    volumes:
      - data_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: draw
      MYSQL_USER: draw
      MYSQL_PASSWORD: draw
    ports:
      - '3306:3306'
  php:
    build:
      context: .docker/php
      args:
        xdebug: 1
    volumes:
      - .:/home/wwwroot
      - ~/.ssh:/home/dev/.ssh
      - ~/.gitconfig:/etc/gitconfig
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - maildev
      - mongodb
    environment:
      IN_CONTAINER: 1

  maildev:
    image: djfarrelly/maildev:latest

    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 8001:80

  mongodb:
    image: "mongo:5.0.0"
    volumes:
      - "data_mongo:/data/db"

volumes:
  data_mysql:
  data_mongo:
