version: '3'
services:
    apache:
        build: .docker/apache
        container_name: draw_apache
        ports:
            - 80:80
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .:/home/wwwroot
        depends_on:
            - php

    mysql:
        image: "mysql:8.0.23"
        container_name: draw_mysql
        command: mysqld --sql_mode=""
        volumes:
            - data_mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: draw
            MYSQL_USER: draw
            MYSQL_PASSWORD: draw
        ports:
            - '3306:3306'
    php:
        build:
            context: .docker/php
            args:
                xdebug: 1
        container_name: draw_php
        volumes:
            - .:/home/wwwroot
            - ~/.ssh:/home/dev/.ssh
            - ~/.gitconfig:/etc/gitconfig
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
            - maildev
        environment:
            IN_CONTAINER: 1

    maildev:
        image: djfarrelly/maildev:latest
        container_name: draw_maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - 8001:80

volumes:
    data_mysql:
