version: '3'

services:
  web:
    image: nginx:1.19-alpine
    container_name: draw_web
    ports:
      - '80:80'
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./var/log/nginx/:/var/log/nginx:cached
      - .:/home/wwwroot
    depends_on:
      - php

  mysql:
    image: "mysql:8.0.23"
    container_name: draw_mysql
    command: mysqld --sql_mode=""
    volumes:
      - data_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: draw
      MYSQL_USER: draw
      MYSQL_PASSWORD: draw
    ports:
      - '3306:3306'
  php:
    build:
      context: .docker/php
      args:
        xdebug: 1
    container_name: draw_php
    volumes:
      - .:/home/wwwroot
      - ~/.ssh:/home/dev/.ssh
      - ~/.gitconfig:/etc/gitconfig
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - maildev
    environment:
      IN_CONTAINER: 1

  maildev:
    image: djfarrelly/maildev:latest
    container_name: draw_maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 8001:80

volumes:
  data_mysql:
