help:
	@echo "This makefile is intended mainly for development purpose."
	@echo ""
	@echo "Targets:"
	@echo "    install:   This will setup the development environment"
	@echo "    up:        docker-compose up the development environment"
	@echo "    down:      docker-compose down the development environment"
	@echo "    test:      run all the vendor/bin/phpunit"
	@echo "    workspace: connect via bash to the workspace container"
	@echo "    clear:     clear all data generated by the build process, this include the database"
	@echo "    provision: provision the data, this should be executed after a clear"
	@echo "    test:          run all the test via vendor/bin/phpunit"
	@echo "    test-coverage: run all the test with html code coverage report"

.ONESHELL:
down:
	if [ -d laradock ]; then
		cd laradock && docker-compose down
	fi

up:
	cd laradock && docker-compose up -d workspace

test:
	cd laradock && docker-compose exec --user=laradock workspace vendor/bin/phpunit

workspace:
	cd laradock && docker-compose exec --user=laradock workspace bash

install: clear setup build provision

setup:
	git clone --branch v5.9.0 https://github.com/laradock/laradock.git laradock
	cp laradock.env-dist laradock/.env

build:
	cd laradock && docker-compose build workspace

clear: down
	sudo rm -Rf ~/.laradock/data
	sudo rm -Rf laradock
	sudo rm -Rf vendor

provision: up
	cd laradock && docker-compose exec --user=laradock workspace composer install

test:
	cd laradock && docker-compose exec --user=laradock workspace vendor/bin/phpunit

test-coverage:
	cd laradock && docker-compose exec --user=laradock workspace vendor/bin/phpunit --coverage-html ./app/storage/phpunit/report

subsplit:
	git subsplit publish src/Component/DataTester:https://github.com/mpoiriert/php-data-tester.git
