controllers:
    resource: '../../app/src/Controller/'
    type: 'attribute'


api_controllers:
    resource: '../../app/src/Controller/Api'
    type: 'attribute'
    format: "json"
    prefix: "/api"
