swagger:
    resource: '@DrawFrameworkExtraBundle/Resources/config/routing-open-api.yaml'

test:
    resource: '../../packages/open-api/Tests/Mock/Controller/TestController.php'
    type: 'attribute'
    format: 'json'
