language: php
php:
  - 5.6
  - 7.0
  - 7.2

env:
  - PHP_UNIT_VERSION="5.7"
  - PHP_UNIT_VERSION="6.0"

matrix:
  exclude:
  - env: PHP_UNIT_VERSION="6.0"
    php: 5.6


before_script:
  - composer require phpunit/phpunit:${PHP_UNIT_VERSION}
  - composer install --dev
