App\Entity\User:
    properties:
        onHoldMessages:
            exclude: true
        messageQueue:
            exclude: true
        needChangePassword:
            exclude: true
        plainPassword:
            expose: true
            type: 'string'
        roles:
            exclude: true
        password:
            exclude: true
        address:
            type: 'App\Entity\Address'
        userAddresses:
            type: 'ArrayCollection<App\Entity\UserAddress>'
            accessor:
                setter: 'setUserAddresses'
