App\Entity\User:
    properties:
        address:
            type: 'App\Entity\Address'
        childObject1:
            exclude: true
        childObject2:
            exclude: true
        manualLock:
            exclude: true
        messageQueue:
            exclude: true
        needChangePassword:
            exclude: true
        onHoldMessages:
            exclude: true
        password:
            exclude: true
        plainPassword:
            expose: true
            type: 'string'
        roles:
            exclude: true
        userAddresses:
            type: 'ArrayCollection<App\Entity\UserAddress>'
            accessor:
                setter: 'setUserAddresses'
        userLocks:
            exclude: true
        totpSecret:
            exclude: true
        forceEnablingTwoFactorAuthentication:
            exclude: true
        emailAuthCode:
            exclude: true
        emailAuthCodeGeneratedAt:
            exclude: true
        twoFactorAuthenticationEnabledProviders:
            exclude: true
