parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

imports:
    - { resource: 'legacy.php' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.

    Draw\Component\Tester\Command\DumpAssertMethodsCommand: ~
    Draw\Component\Tester\Command\GenerateTraitCommand: ~
    Draw\Component\Tester\Command\GenerateAssertsDocumentationPageCommand: ~

    # Sonata Admin services >>>
    Draw\Bundle\SonataExtraBundle\ActionableAdmin\Extension\DefaultActionExtension:
        class: 'Draw\Bundle\SonataExtraBundle\ActionableAdmin\Extension\DefaultActionExtension'
        arguments:
            $actions: ['delete']
        tags:
            - { name: sonata.admin.extension, global: true }
    # Sonata Admin services <<<

    App\:
        resource: '../app/src'
        exclude:
            - '../app/src/{DependencyInjection,Entity,Migrations,Message,Tests,DTO}'
            - '../app/src/Kernel.php'
    App\Controller\:
        resource: '../app/src/Controller'
        tags: [ 'controller.service_arguments' ]

    Symfony\Component\Security\Core\User\UserProviderInterface: '@security.user.provider.concrete.chain_provider'

    jms_serializer.serialized_name_annotation_strategy:
        class: 'JMS\Serializer\Naming\SerializedNameAnnotationStrategy'
        arguments:
            - '@jms_serializer.identical_property_naming_strategy'
