name: After Split Testing

on:
  pull_request: null

env:
  COMPOSER_ROOT_VERSION: 'dev-master'
  DATABASE_URL: 'mysql://root@127.0.0.1:3306/draw'

jobs:
  after_split_testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_name:
          - application
          - aws-tool-kit
          - console
          - core
          - cron-job
          - doctrine-extra
          - entity-migrator
          - fixer
          - framework-extra-bundle
          - log
          - mailer
          - messenger
          - open-api
          - process
          - profiling
          - security
          - sonata-integration-bundle
          - sonata-extra-bundle
          - tester
          - tester-bundle
          - user-bundle
          - validator
          - workflow

    name: After Split Testing of ${{ matrix.package_name }}

    steps:
      
      - name: Checkout
        uses: 'actions/checkout@v2'

      - name: PHP Setup
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.1'
          coverage: none

      - name: Setup MySQL
        uses: 'shogo82148/actions-setup-mysql@v1'
        with:
          mysql-version: 8.0
          distribution: mysql
          auto-start: true

      - name: Create Database
        run: |
          mysql -h 127.0.0.1 -uroot -e "CREATE DATABASE draw"

      - name: 'Composer Setup'
        run: |
          composer install --no-progress
          vendor-bin/monorepo/vendor/bin/monorepo-builder localize-composer-paths
          cd packages/${{ matrix.package_name }}
          composer update --no-progress

      - name: 'Automation Test'
        run: |
          cd packages/${{ matrix.package_name }}
          vendor/bin/phpunit
