---
# https://docs.github.com/en/actions/reference/environment-variables#about-environment-variables
# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
# https://github.com/marketplace/actions/checkout
# https://github.com/marketplace/actions/webfactory-ssh-agent
# https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
# https://github.com/marketplace/actions/setup-php-action
# https://github.com/marketplace/actions/actions-setup-mysql
# https://github.com/marketplace/actions/actions-setup-redis
# https://github.com/marketplace/actions/mongodb-in-github-actions
# https://github.com/marketplace/actions/cache

name: PHP

on:
  push:
  release:
    types:
      - created

jobs:
  automation_test_lowest:
    name: Automation Test [Lowest]
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'mysql://root@127.0.0.1:3306/draw'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer
          coverage: none
          extensions: mongodb-1.7.4
          ini-values: memory_limit=4G
      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: 5.7
          distribution: mysql
          auto-start: true
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-v3-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Build
        run: |

          echo "::group::Install"
          composer update --optimize-autoloader --no-interaction --prefer-dist --prefer-lowest
          bin/console assets:install ./public --no-interaction
          echo "::endgroup::"

          echo "::group::Script"
          php bin/console doctrine:database:create --no-interaction
          php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration -q
          php bin/console doctrine:fixtures:load --no-interaction
          php bin/console messenger:setup-transports --no-interaction
          TRAVIS=1 vendor/bin/phpunit --testdox -v
          echo "::endgroup::"

  automation_test_highest:
    name: Automation Test [Highest]
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'mysql://root@127.0.0.1:3306/draw'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer
          coverage: none
          extensions: mongodb-1.7.4
          ini-values: memory_limit=4G
      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: 5.7
          distribution: mysql
          auto-start: true
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-v3-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Build
        run: |

          echo "::group::Install"
          composer install --optimize-autoloader --no-interaction --prefer-dist
          composer update --optimize-autoloader --no-interaction --prefer-dist
          bin/console assets:install ./public --no-interaction
          echo "::endgroup::"

          echo "::group::Script"
          php bin/console doctrine:database:create --no-interaction
          php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration -q
          php bin/console doctrine:fixtures:load --no-interaction
          php bin/console messenger:setup-transports --no-interaction
          TRAVIS=1 vendor/bin/phpunit --testdox -v
          echo "::endgroup::"
